version: "3"

services:
  bot-discord:
    container_name: bot-discord
    restart: always
    build: .
    environment:
      - TOKEN=CONFIGURAR-TOKEN-AQUI
    working_dir: /bot-discord
    volumes:
      - /home/pi/bot-discord:/bot-discord
    command: "python3 -u bot.py"
